modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="calemieconomy"
version="1.0.15"
displayName="Calemi's Economy"
authors="Calemi"
credits="Calemi - Programmer & Artist"
description='''
    This mod adds a fully-functioning economy to the game.
    '''

[[dependencies.calemieconomy]]
    modId="calemicore"
    mandatory=true
    versionRange="1.0.14"
    ordering="NONE"
    side="BOTH"

[[dependencies.calemieconomy]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.calemieconomy]]
    modId="minecraft"
    mandatory=true
    versionRange="1.18.2"
    ordering="NONE"
    side="BOTH"
